"""empty message

Revision ID: 742721ae13ab
Revises: 3248b00591ab
Create Date: 2020-12-20 13:29:06.548562

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '742721ae13ab'
down_revision = '3248b00591ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roles', sa.Column('default', sa.Boolean(), nullable=True))
    op.add_column('roles', sa.Column('permissions', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_roles_default'), 'roles', ['default'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_roles_default'), table_name='roles')
    op.drop_column('roles', 'permissions')
    op.drop_column('roles', 'default')
    # ### end Alembic commands ###
